server:
  port: 8090
  servlet:
    context-path: /mf-register-api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mf_dev_register?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 11270922
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    table: schema_version
    enabled: true
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd'T'HH:mm:ss
